import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout from '../../components/layout'
import styles from './personal.module.css'
import { useState } from 'react'

import { Button } from 'react-bootstrap'

export default function Personal( {...props}) {
    const [ isLoading, setIsLoading ] = useState(false)

  return (
    <Layout home>
      <Head>
        <title>Personal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <h1 className={styles.title}>
          Personal
        </h1>
        <div className={styles.container}></div>
        <div className={styles.formBox}>
          <div className={styles.grid}>
              <h2>Personal &rarr;</h2>
              <p>test</p>
              <form action="">
                  <input type="text" />
                  <Button>submit</Button>
              </form>
          </div>

        </div>
       </main>
    </Layout>
    )
}