import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout from '../../components/layout'
import styles from './achieve.module.css'

import { dbConnect } from '../../utils/dbConnect'
import CanadaCustomsInvoice from '../../models/CanadaCustomsInvoice'

export default function Achieve( { canadaCustomsInvoices }) {
  return (
    <Layout home>
      <Head>
        <title>Documentation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <h1 className={styles.title}>
          My Achieve
        </h1>
        { canadaCustomsInvoices.map((invoice => (
           <div key={invoice._id}>
                <div className={styles.formBox}>
                    <div className={styles.grid}>
                        <Link href={`/achieve/${invoice._id}`}>
                            <a className={styles.card}>
                            <h2>{invoice.formType} &rarr;</h2>
                            <div><p>{invoice.createdAt}</p></div>
                            <div><p>{invoice.shipperAddress}</p></div>
                            {/* <p>Updated at {invoice.createdAt}</p>
                            <p>Updated at {invoice.updatedAt}</p> */}
                            {/* <p>{ObjectId("621e23407d301fa19a38b548").getTimestamp()}</p> */}
                            </a>
                        </Link>
                    </div>
                </div>
           </div>
        )))}
        <div className={styles.container}>
           
        </div>
       </main>
    </Layout>
    )
}

export async function getServerSideProps() {
    await dbConnect()
  
    const result = await CanadaCustomsInvoice.find({})
    
    const canadaCustomsInvoices = result.map((doc) => {
      const invoice = doc.toObject()
      invoice._id = doc._id.toString()
      return invoice
    })
  
    return { props: { canadaCustomsInvoices: canadaCustomsInvoices } }
  }